#!/usr/bin/env python3
"""
Dark Factory - YouTube Uploader
Uploads generated content to YouTube
"""
import os
import json
import pickle
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# If modifying these scopes, delete the file token.pickle.
SCOPES = ['https://www.googleapis.com/auth/youtube.upload']

def get_authenticated_service():
    """Get authenticated YouTube API service"""
    creds = None
    
    # Get credentials from environment variable
    creds_json = os.getenv("YOUTUBE_CREDENTIALS")
    if not creds_json:
        raise ValueError("YOUTUBE_CREDENTIALS environment variable not set")
    
    # Write to temporary file
    with open("temp_credentials.json", "w") as f:
        f.write(creds_json)
    
    flow = InstalledAppFlow.from_client_secrets_file(
        "temp_credentials.json", SCOPES)
    
    # Run local server for authentication
    creds = flow.run_local_server(port=8080, open_browser=False)
    
    # Clean up
    os.remove("temp_credentials.json")
    
    return build('youtube', 'v3', credentials=creds)

def upload_video(youtube, file_path, title, description):
    """Upload a video to YouTube"""
    body = {
        'snippet': {
            'title': title,
            'description': description,
            'tags': ['automated', 'ai', 'technology'],
            'categoryId': '28'  # Science & Technology
        },
        'status': {
            'privacyStatus': 'private',  # Start as private for testing
            'selfDeclaredMadeForKids': False
        }
    }
    
    # In a real implementation, you would upload an actual video file
    # For now, we'll just simulate the upload
    print(f"📤 Would upload video: {title}")
    print(f"   Description: {description[:50]}...")
    print("   Privacy: private (change to 'public' when ready)")
    
    return {"id": "simulated_video_id", "title": title}

def main():
    print("🏭 DARK FACTORY - YOUTUBE UPLOADER")
    print("=" * 50)
    
    # Check credentials
    if not os.getenv("YOUTUBE_CREDENTIALS"):
        print("❌ ERROR: YOUTUBE_CREDENTIALS environment variable not set")
        return 1
    
    print("✅ YouTube credentials loaded")
    
    try:
        # Get authenticated service
        print("🔐 Authenticating with YouTube API...")
        youtube = get_authenticated_service()
        print("✅ Authentication successful")
        
        # Read generated content
        if os.path.exists("latest_content.txt"):
            with open("latest_content.txt", "r") as f:
                content = f.read()
            
            # Create video metadata
            title = f"Auto-Generated Video {os.urandom(2).hex()}"
            description = f"Automatically generated content:\n\n{content[:2000]}..."
            
            # Simulate upload (remove in production)
            print("🎬 Simulating video upload...")
            result = upload_video(youtube, "simulated.mp4", title, description)
            
            print(f"✅ Upload simulated: {result['title']}")
            print("   Note: In production, replace with actual video file upload")
            
        else:
            print("⚠️  No content found. Run content_generator.py first.")
            print("   Creating sample upload...")
            
            # Sample upload
            title = "Dark Factory Test Video"
            description = "Automatically generated by Dark Factory"
            result = upload_video(youtube, "sample.mp4", title, description)
            
            print(f"✅ Sample upload: {result['title']}")
        
        return 0
        
    except Exception as e:
        print(f"❌ YouTube API error: {type(e).__name__}: {e}")
        return 1

if __name__ == "__main__":
    exit_code = main()
    exit(exit_code)
